-- Insert data into the person table
INSERT INTO person (first_name, last_name, gender, date_of_birth, nation, email)
VALUES
    ('Ana', 'Cacho Paulo', 'Female', '1999-09-22', 'Portugal', 'anacachopaulo@gmail.com'),
    ('Jacinto', 'Leito Capelo Rego', 'Male', '1990-07-22', 'Portugal', 'Jacintoleitecapelorego@gmail.com'),
    ('Tomas', 'Turbando', 'Male', '2004-10-12', 'Portugal', 'tomasturbando@gmail.com'),
    ('Simas', 'Turbo', 'Male', '2000-03-15', 'Portugal', 'simasturbo12@gmail.com'),
    ('Bruno', 'Costa', 'Male', '2002-02-25', 'Portugal', 'brubru@gmail.com'),
    ('Maria', 'Silva', 'Female', '1995-12-10', 'Portugal', 'mariasilva@example.com'),
    ('João', 'Pereira', 'Male', '1988-05-20', 'Portugal', 'joaopereira@example.com'),
    ('Carla', 'Santos', 'Female', '1979-03-18', 'Portugal', 'carlasantos@example.com'),
    ('Rui', 'Fernandes', 'Male', '1993-08-27', 'Portugal', 'ruifernandes@example.com'),
    ('Sara', 'Gonçalves', 'Female', '2001-11-15', 'Portugal', 'saragoncalves@example.com'),
    ('Manuel', 'Lopes', 'Male', '1985-04-30', 'Portugal', 'manuel.lopes@example.com'),
    ('Catarina', 'Martins', 'Female', '1992-11-05', 'Portugal', 'catarina.martins@example.com'),
    ('Pedro', 'Sousa', 'Male', '1977-08-17', 'Portugal', 'pedro.sousa@example.com'),
    ('Inês', 'Rodrigues', 'Female', '1983-12-22', 'Portugal', 'ines.rodrigues@example.com'),
    ('Hugo', 'Ferreira', 'Male', '1998-06-10', 'Portugal', 'hugo.ferreira@example.com'),
    ('Ana', 'Almeida', 'Female', '1972-09-14', 'Portugal', 'ana.almeida@example.com'),
    ('Miguel', 'Pinto', 'Male', '1989-02-28', 'Portugal', 'miguel.pinto@example.com'),
    ('Sofia', 'Carvalho', 'Female', '1996-07-03', 'Portugal', 'sofia.carvalho@example.com'),
    ('Ricardo', 'Gomes', 'Male', '1974-05-18', 'Portugal', 'ricardo.gomes@example.com'),
    ('Beatriz', 'Duarte', 'Female', '1981-10-25', 'Portugal', 'beatriz.duarte@example.com'),
    ('John', 'Doe', 'Male', '1990-03-15', 'USA', 'johndoe@example.com'),
    ('Alice', 'Smith', 'Female', '1985-08-22', 'UK', 'alice.smith@example.com'),
    ('Mohammed', 'Abdul', 'Male', '1983-05-10', 'UAE', 'mohammed.abdul@example.com'),
    ('Anna', 'Müller', 'Female', '1993-11-18', 'Germany', 'anna.mueller@example.com'),
    ('Juan', 'García', 'Male', '1988-07-25', 'Spain', 'juan.garcia@example.com'),
    ('Sophie', 'Dubois', 'Female', '1979-04-29', 'France', 'sophie.dubois@example.com'),
    ('Ahmed', 'Ali', 'Male', '1980-09-12', 'Egypt', 'ahmed.ali@example.com'),
    ('Maria', 'Rossi', 'Female', '1995-02-08', 'Italy', 'maria.rossi@example.com'),
    ('Chen', 'Li', 'Male', '1987-06-03', 'China', 'chen.li@example.com'),
    ('Aya', 'Suzuki', 'Female', '1990-10-20', 'Japan', 'aya.suzuki@example.com');

